spring.application.name=gerenciador-agendamentos

# Pede para o tradutor (JPA) criar a tabela automaticamente pra gente
spring.jpa.hibernate.ddl-auto=update

# Porta para a conexao com o render
server.port=${PORT:8080}